Magazzino: Magazzino.o Articolo.o
	g++ Magazzino.o Articolo.o -o Magazzino
Magazzino.o: Magazzino.cpp Articolo.h
	g++ -c Magazzino.cpp --std=c++11 -Wall -pedantic -o Magazzino.o
Articolo.o: Articolo.cpp Articolo.h
	g++ -c Articolo.cpp --std=c++11 -Wall -pedantic -o Articolo.o